export const AUTHORIZATION_KEY = process.env.AUTHORIZATION_KEY;
export const AUTHORIZATION_USER = process.env.AUTHORIZATION_USER;
export const AUTHORIZATION_PASSWORD = process.env.AUTHORIZATION_PASSWORD;